# not specifying a source means we don't go out to rubygems.org at build time
#source 'https://rubygems.org'

gem 'rails', '>= 3.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Shouldn't need this for anything
#gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
# Hawk doesn't use these yet at all...
group :assets do
#  gem 'sass-rails',   '~> 3.2.3'
#  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

#  gem 'uglifier', '>= 1.0.3'
end

# Hawk doesn't use this yet either
#gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

gem 'fast_gettext'
 
# 0.4.3 contains fixes in
#'rake gettext:store_model_attributes' task
gem 'gettext_i18n_rails', '>= 0.4.3'

# rails-i18n provides translations for ActiveRecord
# validation error messages
gem 'rails-i18n'

# needed to collect translatable strings
# not needed at production
group :development do
  # needed for HAML support (optional)
  # TODO(rails): don't need this yet, I reckon...
  #gem 'ruby_parser'

  # no need to load the gem via require
  # we only need the rake tasks
  gem 'gettext', '>= 1.9.3', :require => false
end

# TODO(rails): do we still need this?
#gem 'rack'

group :test do
  gem 'rake'
end

