# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

#
# Note: When using Bundler (i.e. on SLES), the Gemfile is used.
# Anywhere else, we don't package the Gemfile, so need to require
# rails, fast_gettext, etc. in config/boot.rb, i.e. if we add more
# gems here, they need to go in config/boot.rb as well. Yes, this
# sucks, but it's the least-worst solution I can find right now for
# making Bundler go away when we neither need nor want it.
#
# Have I mentioned lately that while Bundler may be "the best way to
# manage a Ruby application's gems", it's an absolute menace if you're
# trying to build packaged software?
#

gem "rails", "~> 4.2.0"
gem "puma", ">= 2.16"
gem "sass-rails", "~> 5.0.1"
gem "virtus", "~> 1.0.4"
gem "js-routes", "~> 1.0"
gem "tilt", "~> 1.4.1"
gem "fast_gettext", ">= 0.9.2"
gem "gettext_i18n_rails_js", "~> 1.0"
gem "gettext_i18n_rails", "~> 1.2"

gem "sprockets", ">= 3.0.0"
gem "kramdown", ">= 1.3.3"

group :development do
  gem "web-console", "~> 2.1", require: false
  gem "spring", ">= 1.3"
  gem "uglifier"
  gem "gettext", "~> 3.1", require: false
end

group :test do
  if ENV["RAILS_ENV"] == "test"
    source "https://rubygems.org"

    gem "rubocop"
    gem "rake"
    gem "brakeman"

    gem "rspec-rails", "~> 3.4.2"
    gem "capybara", "~> 2.7.1"
    gem "guard-rspec", "~> 4.7.2"
  end
end

instance_eval(File.read("Gemfile.local")) if File.exist? "Gemfile.local"
