# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

FileUtils.mkdir_p [
  "tmp/pids",
  "tmp/sessions",
  "tmp/sockets",
  "tmp/cache"
]

require ::File.expand_path("../config/application", __FILE__)
Rails.application.load_tasks
